### PR TITLE
Add preadjust goal recovery

### PR DESCRIPTION
**Pull request by howardcochran**
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11)

### CODE REVIEW

**Comment by c-andy-martin** [comment]
___
*[include/teb_local_planner/timed_elastic_band.h, line 513 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wYnrl1NM8hXiKQvQC:-M5wYnrl1NM8hXiKQvQD:blcsec8) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/f53ee06b558b1720b931c3306750c944fa1cd2f5/include/teb_local_planner/timed_elastic_band.h#L513)):*
> ```objc
>    */
>   void setPoseVertexFixed(int index, bool status);
>   PoseSE2& nominalGoal() {return nominal_goal_;}
> ```

the c++ style guide suggests spaces inside the braces:
https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace

**Comment by c-andy-martin** [comment]
___
*[src/optimal_planner.cpp, line 258 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5we4YWE1YtlFaXEp7d:-M5we4YWE1YtlFaXEp7e:b-9dypfu) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/018fdbd78242c8ccca3af13728c8da1b4c084a8e/src/optimal_planner.cpp#L258)):*
> ```cpp
>     }
>     // No open pose found. Just return the furthest one back (the robot's current pose)
>     return teb_.Pose(0);
> ```

is it guaranteed that teb_.sizePoses() > 0?

**Comment by c-andy-martin** [comment]
___
*[src/optimal_planner.cpp, line 258 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5we4YWE1YtlFaXEp7d:-M5weCJw7H7nvyP2xDk4:bsqjyri) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/018fdbd78242c8ccca3af13728c8da1b4c084a8e/src/optimal_planner.cpp#L258)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

is it guaranteed that teb_.sizePoses() > 0?
</blockquote></details>

oh, duh, I see you checked for that a few lines below

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
Seems like we should squash the last three commits to get rid of the FIXMEs and fixed constants in the 3rd from last commit.

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-:-M5wgZwvAPU1sLTYXWJi:bwvltxs)* status: all files reviewed, 7 unresolved discussions (waiting on @howardcochran)

___
*[include/teb_local_planner/pose_se2.h, line 295 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wXvl4-LWTXUYOBd1A:-M5wXvl57sB8fy16TsXc:bc6zw7u) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/f53ee06b558b1720b931c3306750c944fa1cd2f5/include/teb_local_planner/pose_se2.h#L295)):*
> ```objc
>   ///@{ 
>   
>   bool operator==( const PoseSE2& rhs )
> ```

nitpick, I think the spaces inside the parens here are unnecessary.
___
*[include/teb_local_planner/pose_se2.h, line 297 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wYS_N2d-ig4by3kGn:-M5wYS_N2d-ig4by3kGo:bscngqe) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/f53ee06b558b1720b931c3306750c944fa1cd2f5/include/teb_local_planner/pose_se2.h#L297)):*
> ```objc
>   bool operator==( const PoseSE2& rhs )
>   {
>     if (&rhs == this)
> ```

do you think this is necessary? Seems like adding the branch and extra test is unnecessary since the test below will cover the case that it's the same object just fine
___
*[include/teb_local_planner/pose_se2.h, line 302 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wYDl-3xtCDxspUofM:-M5wYDl-3xtCDxspUofN:bps1s89) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/f53ee06b558b1720b931c3306750c944fa1cd2f5/include/teb_local_planner/pose_se2.h#L302)):*
> ```objc
>   }
> 
>   bool operator!=( const PoseSE2& rhs )
> ```

here too
___
*[include/teb_local_planner/timed_elastic_band.h, line 101 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wYic2B6Wn2A8UfuQT:-M5wYic2B6Wn2A8UfuQU:b-mtiib7) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/f53ee06b558b1720b931c3306750c944fa1cd2f5/include/teb_local_planner/timed_elastic_band.h#L101)):*
> ```objc
> 
>   
>   /** @name Access pose and timediff sequences */
> ```

removed horizontal whitespace outside of the changes, my guess is this is accidental
___
*[include/teb_local_planner/timed_elastic_band.h, line 202 at r5](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5whQig5bd1ZTsVRE4z:-M5whQig5bd1ZTsVRE5-:b-w39awt) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/460ceca7757d82864cfe70681c9ddf18a963b6f1/include/teb_local_planner/timed_elastic_band.h#L202)):*
> ```objc
>     return pose_vec_.at(index);
>   }
> ```

another whitespace only change
___
*[src/optimal_planner.cpp, line 191 at r5](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wgKBi3J6tB5gEdL4O:-M5wgKBj5XKTg9iga3Px:b5v4si2) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/460ceca7757d82864cfe70681c9ddf18a963b6f1/src/optimal_planner.cpp#L191)):*
> ```cpp
>   {
>     // The reason this if is written this way is so that it will be true if value is NaN
>     if (!(distFromNominalGoal(preadjust_prev_adjusted_goal_) < cfg_->recovery.preadjust_stability_nominal_goal_change_dist))
> ```

so, is it OK not to check theta? If theta changes by a lot, we don't adopt the new x/y position. Seems like we might want that.

**Review by howardcochran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11)* status: 6 of 10 files reviewed, 7 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[include/teb_local_planner/pose_se2.h, line 295 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wXvl4-LWTXUYOBd1A:-M61PamF0GWBTE4Ehlp1:bsaj69h) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/f53ee06b558b1720b931c3306750c944fa1cd2f5/include/teb_local_planner/pose_se2.h#L295)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

nitpick, I think the spaces inside the parens here are unnecessary.
</blockquote></details>

Very true.  I just copy/pasted upstream's operator= declaration which had those spaces.  Removed.
___
*[include/teb_local_planner/pose_se2.h, line 297 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wYS_N2d-ig4by3kGn:-M61Pjyc88oQ89-9BAFw:b-2xi18k) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/f53ee06b558b1720b931c3306750c944fa1cd2f5/include/teb_local_planner/pose_se2.h#L297)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

do you think this is necessary? Seems like adding the branch and extra test is unnecessary since the test below will cover the case that it's the same object just fine
</blockquote></details>

Not necessary. Just boilerplate for an operator== definition.  But not really helpful, so removed.
___
*[include/teb_local_planner/pose_se2.h, line 302 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wYDl-3xtCDxspUofM:-M61PuFQ4NIinc9uPQvG:bs7wumb) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/f53ee06b558b1720b931c3306750c944fa1cd2f5/include/teb_local_planner/pose_se2.h#L302)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.
___
*[include/teb_local_planner/timed_elastic_band.h, line 513 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wYnrl1NM8hXiKQvQC:-M61Sxgs9HSTArzKdSRE:bg9j5d7) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/f53ee06b558b1720b931c3306750c944fa1cd2f5/include/teb_local_planner/timed_elastic_band.h#L513)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

the c++ style guide suggests spaces inside the braces:
https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace
</blockquote></details>

Fixed. I was trying to be consistent with upstream even though they deviate from guide. But I see that they're rather inconsistent anyway, so might as well do it right.
___
*[src/optimal_planner.cpp, line 258 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5we4YWE1YtlFaXEp7d:-M5wicoJ482EMwZJQCp4:b2nhswv) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/018fdbd78242c8ccca3af13728c8da1b4c084a8e/src/optimal_planner.cpp#L258)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

oh, duh, I see you checked for that a few lines below
</blockquote></details>

Yep
___
*[src/optimal_planner.cpp, line 191 at r5](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wgKBi3J6tB5gEdL4O:-M61W8U01t8fVie4FSs7:b-6ihqt2) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/460ceca7757d82864cfe70681c9ddf18a963b6f1/src/optimal_planner.cpp#L191)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

so, is it OK not to check theta? If theta changes by a lot, we don't adopt the new x/y position. Seems like we might want that.
</blockquote></details>

Yes, I think it is OK. At one point I added " || (theta changed)" to this if but it caused constant resetting due to micro changes of theta from the localizer, so I'd need another threshold, but am not sure what that should be.  Since I unconditionally adopt theta differences, and because this is irrelevant when the goal is not blocked by an obstacle, failure to make a small adjustment to the nominal X, Y in this case doesn't really matter.

**Review by howardcochran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11)* status: 6 of 10 files reviewed, 7 unresolved discussions (waiting on @c-andy-martin)

___
*[include/teb_local_planner/timed_elastic_band.h, line 101 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5wYic2B6Wn2A8UfuQT:-M61aiCx1vGgi5gnkj5n:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/f53ee06b558b1720b931c3306750c944fa1cd2f5/include/teb_local_planner/timed_elastic_band.h#L101)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

removed horizontal whitespace outside of the changes, my guess is this is accidental
</blockquote></details>

Done.
___
*[include/teb_local_planner/timed_elastic_band.h, line 202 at r5](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-M5whQig5bd1ZTsVRE4z:-M61aiYV0n3Ym1QOOk8-:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/460ceca7757d82864cfe70681c9ddf18a963b6f1/include/teb_local_planner/timed_elastic_band.h#L202)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

another whitespace only change
</blockquote></details>

Done.

**Review by c-andy-martin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/11#-:-M61bZ0iCjcx4GGZdiP1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
