### PR TITLE
Replaced boost's next and prior by STL variants

### PR DESCRIPTION
**Pull request by dandedrick**
This is from an upstream patch that doesn't quite apply but I adjusted it to work. We need this for the yocto upgrade that brings a new version of boost that broke compatibility.

Upstream patch:
https://github.com/rst-tu-dortmund/teb_local_planner/commit/8bd805e29ef629a003880e22d67d9529da76a87d

- - -
This change is [Reviewable](https://reviewable.io/reviews/BadgerTechnologies/teb_local_planner/23)

### CODE REVIEW

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/teb_local_planner/23)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dandedrick)

___
*[`include/teb_local_planner/visualization.hpp` line 226 at r1](https://reviewable.io/reviews/BadgerTechnologies/teb_local_planner/23#-Nz-Fe_K8gWA_7uZN3Cf:-Nz-Fe_L8VudtTemyuaC:bmz3mq3) ([raw file](https://github.com/BadgerTechnologies/teb_local_planner/blob/42742989b0b6daec4c49cddb068181a7446847ac/include/teb_local_planner/visualization.hpp#L226)):*
> ```cpp
>   
>   
> } // namespace teb_local_planner
> ```

let's not add a new line here just to minimize changes vs. upstream

**Review by dandedrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/teb_local_planner/23)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @c-andy-martin)

___
*[`include/teb_local_planner/visualization.hpp` line 226 at r1](https://reviewable.io/reviews/BadgerTechnologies/teb_local_planner/23#-Nz-Fe_K8gWA_7uZN3Cf:-Nz-Ns1a019at5FfBeOn:b-896fix) ([raw file](https://github.com/BadgerTechnologies/teb_local_planner/blob/42742989b0b6daec4c49cddb068181a7446847ac/include/teb_local_planner/visualization.hpp#L226)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

let's not add a new line here just to minimize changes vs. upstream
</blockquote></details>

Done.

**Review by c-andy-martin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/teb_local_planner/23)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dandedrick)

**Review by c-andy-martin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/teb_local_planner/23#-:-Nz-OH6E1S1yB9sqm03h:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dandedrick)

**Pull request merged**
