### PR TITLE
New precise control law

### PR DESCRIPTION
**Pull request by howardcochran**
Much more precise control to reduce fish-tailing without cutting
corners

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8)

### CODE REVIEW

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8)* status: 3 of 12 files reviewed, 1 unresolved discussion (waiting on @c-andy-martin and @howardcochran)

___
*[include/teb_local_planner/planner_interface.h, line 59 at r8](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6dp_h7E_PkP2Ndu_N:-Lv6dp_h7E_PkP2Ndu_O:bsaanno) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/74e24e45898f582910f3422e974e3f0cbee35de1/include/teb_local_planner/planner_interface.h#L59)):*
> ```objc
> 
> 
> #include <teb_local_planner/timed_elastic_band.h>
> ```

this include should come immediately after `<teb_local_planner/visualization.h>` I think, with no new extra vertical white space

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 4 files at r2, 1 of 1 files at r6, 1 of 1 files at r9, 2 of 2 files at r10, 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8)* status: all files reviewed, 16 unresolved discussions (waiting on @howardcochran)

___
*[cfg/TebLocalPlannerReconfigure.cfg, line 119 at r11](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6wEt7E1zb9lqG5I3c:-Lv6wEt7E1zb9lqG5I3d:bfnk5dj) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/5f822ec8c0e3b0cf2474e58f4e309d3036c0dfdb/cfg/TebLocalPlannerReconfigure.cfg#L119)):*
> ```INI
> 	"Maximum angular acceleration of the robot", 
> 	0.5, 0.01, 100)  
> ```

please fix whitespace change
___
*[include/teb_local_planner/teb_local_planner_ros.h, line 412 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6jfUXCHviDiSNV5ZN:-Lv6jfUXCHviDiSNV5ZO:bwvn6hr) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/ddba3634294d1986bde438711a213384112ce60d/include/teb_local_planner/teb_local_planner_ros.h#L412)):*
> ```objc
> 
> #endif // TEB_LOCAL_PLANNER_ROS_H_
> ```

I don't think we want to modify WS in order to avoid upstream merge conflicts on WS
___
*[src/teb_local_planner_ros.cpp, line 214 at r9](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6kq6NBchcpPv8ZOkU:-Lv6kq6NBchcpPv8ZOkV:bt7bjzr) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c7b85622573469e89c6d9d77a1c72a979e65101c/src/teb_local_planner_ros.cpp#L214)):*
> ```cpp
> }
> ```

Please remove this WS only change
___
*[src/teb_local_planner_ros.cpp, line 869 at r9](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6iLva1aFIMabM7mpR:-Lv6iLva1aFIMabM7mpS:b-guju7g) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c7b85622573469e89c6d9d77a1c72a979e65101c/src/teb_local_planner_ros.cpp#L869)):*
> ```cpp
>   // we will drive the intended arc.
>   if (fabs(orig_vx) > 1e-3)  // Avoid div by near-zero
>     omega *= vx / orig_vx;
> ```

I think we should also move the vy limiting below vx, and apply the limit factor of `vx / orig_vx` to both omega and `vy`, then do the same thing we do below for omega to `vy` prior to omega, and then have omega scale both vx and vy. Otherwise, the translation vector can still be wrong when we limit vx and not vy, vy and not vx, etc. This won't matter at all for a non-holonomic bot, but teb seems to be able to work for either kind of bot, so I think this code should fix the bug for vx/vy (and all other pairs) as well as vx/omega. We would need to be careful on our bot not to limit `max_vel_y` to zero, or we would not be able to drive if teb spat out a small but non-zero vy. (Or I suppose you could make two versions of this code, one for holonomic and one not?)
___
*[src/teb_local_planner_ros.cpp, line 1172 at r9](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6g5gtCxckVZHBs4ci:-Lv6g5gtCxckVZHBs4cj:buw7ehl) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/ddba3634294d1986bde438711a213384112ce60d/src/teb_local_planner_ros.cpp#L1172)):*
> ```cpp
> } // end namespace teb_local_planner
> ```

I don't think we should delete the (very annoying) extra vertical WS here
___
*[src/teb_local_planner_ros.cpp, line 56 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6jnuh11S9whkd-lX2:-Lv6jnuh11S9whkd-lX3:b-vx26u9) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L56)):*
> ```cpp
> #include "g2o/solvers/csparse/linear_solver_csparse.h"
> #include "g2o/solvers/cholmod/linear_solver_cholmod.h"
> #include "ros/time.h"
> ```

I don't know why the `g2o` includes above are using quotes `"`, but I think we should be using `<` and `>` for sure for including ros files.
___
*[src/teb_local_planner_ros.cpp, line 66 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6kdAACTqcfyEt2Hmu:-Lv6kdAACTqcfyEt2Hmv:b-ttdlst) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L66)):*
> ```cpp
> {
> 
> ros::Publisher debug_control_pose_pub;
> ```

I would strongly prefer these to be member variables over globals
___
*[src/teb_local_planner_ros.cpp, line 407 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6ljAX5etd5lPA14Ud:-Lv6ljAX5etd5lPA14Ue:b-e9g4jv) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L407)):*
> ```cpp
> PoseSE2 slerp_line(const PoseSE2& p1, const PoseSE2& p2, double fraction)
> {
>   double dt = 1.0;
> ```

dt never seems to be set to anything other than 1.0. Can we just remove it?
___
*[src/teb_local_planner_ros.cpp, line 413 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6mSW6AlGlWRFF9NA2:-Lv6mSW6AlGlWRFF9NA3:bphmpg0) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L413)):*
> ```cpp
>   double omega = g2o::normalize_theta(p2.theta() - p1.theta());
> 
>   new_pos.x() = p1.x() + (vx * cos(p1.theta())) * dt * fraction;
> ```

pretty sure the args to cos/sin should be `p1.theta + omega`, not p1.theta. Consider two poses like this:

```

             .---->


 .
/|\
 |
 |
```
If you use p1.theta, the new positions will all be on the direction the bottom vector is pointing (if its p1). If you use `p1.theta + omega`, they will be on the line that connects the bases of the poses. My guess is this causes no practical problems because  slerp_line is only ever used when going roughly in a straight line form poses to pose. However, for such a generally named function, either document the restriction in a comment, or change the calculation.
___
*[src/teb_local_planner_ros.cpp, line 424 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6qi8X2N6bZgkwaW2h:-Lv6qi8X2N6bZgkwaW2i:b-li1s55) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L424)):*
> ```cpp
>   Eigen::Vector2d pos2 = p2.position();
>   double distance = (pos2 - pos1).norm();
>   double radius = distance / (2 * sin(bearing));
> ```

Won't this be a divide by zero if bearing is also +/- pi? Maybe slerp_arc should check if bearing is near 0 or pi and call slerp_line instead of slerp_pose doing it, as if some code in the future ever calls slerp_arc directly, you could get a division by zero.
___
*[src/teb_local_planner_ros.cpp, line 425 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6rvYtDeuCgTSP5J0X:-Lv6rvYtDeuCgTSP5J0Y:b-xr1g67) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L425)):*
> ```cpp
>   double distance = (pos2 - pos1).norm();
>   double radius = distance / (2 * sin(bearing));
>   double angle = g2o::normalize_theta(2 * bearing) * fraction;
> ```

should this instead be `angle = g2o::normalize_theta(p2.theta - p1.theta) * fraction`? Otherwise, won't you be slerping between the starting orientation and the bearing, which won't necessarily line up with the orientation of the final pose? Consider the same example I put on the slerp_line comment, you would end up w/ the final orientation at a fraction of 1.0 being 45 degrees instead of 90.
___
*[src/teb_local_planner_ros.cpp, line 440 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6q_fd5qxVRDqVS2IW:-Lv6q_fd5qxVRDqVS2IX:bs75aa7) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L440)):*
> ```cpp
>   Eigen::Vector2d displacement = p2.position() - p1.position();
>   double bearing = g2o::normalize_theta(atan2(displacement[1], displacement[0]) - p1.theta());
>   if (fabs(bearing) < 1e-4)
> ```

I think you should also be checking for a bearing near +/- pi as that will cause a division by zero as well in slerp_arc
___
*[src/teb_local_planner_ros.cpp, line 458 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6uY6HC-Pd0SVAEPrg:-Lv6uY6HC-Pd0SVAEPrh:b8nci9f) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L458)):*
> ```cpp
>   {
>     cur_time_diff = teb.TimeDiff(i);
>     if (cumulative_time <= seconds && seconds < cumulative_time + cur_time_diff)
> ```

I don't think the first check is necessary, pretty sure you can just simplify this to `seconds < cumulative_time + cur_time_diff`
___
*[src/teb_local_planner_ros.cpp, line 478 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6smJj-fozgnIpGg9j:-Lv6smJj-fozgnIpGg9k:bsdzxok) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L478)):*
> ```cpp
> {
>   double min_dist = std::numeric_limits<double>::max();
>   double time_with_min_dist;
> ```

if start_time > end_time you will return whatever happens to be on the stack here. I would initialize this to `start_time`.
___
*[src/teb_local_planner_ros.cpp, line 601 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6vZbp2R57neL7O75F:-Lv6vZbp2R57neL7O75G:b-5aqj8h) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L601)):*
> ```cpp
>     Eigen::Rotation2D<double> R(-robot_pose.theta());
>     Eigen::Matrix2d ctrl_point_matrix;
>     ctrl_point_matrix << 1, 0, 0, 1/ctrl_point_displacement;
> ```

I assume the control point displacement is guaranteed to never be zero? Maybe make a comment here?

**Comment by c-andy-martin** [comment]
___
*[src/teb_local_planner_ros.cpp, line 425 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6rvYtDeuCgTSP5J0X:-Lv7LevB2YDa_mJP_Q-w:bw7itc0) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L425)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

should this instead be `angle = g2o::normalize_theta(p2.theta - p1.theta) * fraction`? Otherwise, won't you be slerping between the starting orientation and the bearing, which won't necessarily line up with the orientation of the final pose? Consider the same example I put on the slerp_line comment, you would end up w/ the final orientation at a fraction of 1.0 being 45 degrees instead of 90.
</blockquote></details>

Ah, I think I understand why, because such a curve would be un-achievable by a non-holonomic robot, as the bot would not be pointing in the direction of travel.

**Review by howardcochran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8)* status: 8 of 12 files reviewed, 16 unresolved discussions (waiting on @c-andy-martin)

___
*[cfg/TebLocalPlannerReconfigure.cfg, line 119 at r11](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6wEt7E1zb9lqG5I3c:-Lv7GDb5BeW4Jlsh-EnG:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/5f822ec8c0e3b0cf2474e58f4e309d3036c0dfdb/cfg/TebLocalPlannerReconfigure.cfg#L119)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

please fix whitespace change
</blockquote></details>

Done.
___
*[include/teb_local_planner/planner_interface.h, line 59 at r8](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6dp_h7E_PkP2Ndu_N:-Lv7Gc1P6HAWZ3iWbKqx:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/74e24e45898f582910f3422e974e3f0cbee35de1/include/teb_local_planner/planner_interface.h#L59)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this include should come immediately after `<teb_local_planner/visualization.h>` I think, with no new extra vertical white space
</blockquote></details>

Done.
___
*[include/teb_local_planner/teb_local_planner_ros.h, line 412 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6jfUXCHviDiSNV5ZN:-Lv7GsWR4L3oA5EmVYWY:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/ddba3634294d1986bde438711a213384112ce60d/include/teb_local_planner/teb_local_planner_ros.h#L412)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't think we want to modify WS in order to avoid upstream merge conflicts on WS
</blockquote></details>

Done.
___
*[src/teb_local_planner_ros.cpp, line 214 at r9](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6kq6NBchcpPv8ZOkU:-Lv7XdTu9U5gSWI1I6Xd:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c7b85622573469e89c6d9d77a1c72a979e65101c/src/teb_local_planner_ros.cpp#L214)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Please remove this WS only change
</blockquote></details>

Done.
___
*[src/teb_local_planner_ros.cpp, line 869 at r9](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6iLva1aFIMabM7mpR:-Lv7KEbfEHrFBkxvdb9J:b-rutb6r) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c7b85622573469e89c6d9d77a1c72a979e65101c/src/teb_local_planner_ros.cpp#L869)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I think we should also move the vy limiting below vx, and apply the limit factor of `vx / orig_vx` to both omega and `vy`, then do the same thing we do below for omega to `vy` prior to omega, and then have omega scale both vx and vy. Otherwise, the translation vector can still be wrong when we limit vx and not vy, vy and not vx, etc. This won't matter at all for a non-holonomic bot, but teb seems to be able to work for either kind of bot, so I think this code should fix the bug for vx/vy (and all other pairs) as well as vx/omega. We would need to be careful on our bot not to limit `max_vel_y` to zero, or we would not be able to drive if teb spat out a small but non-zero vy. (Or I suppose you could make two versions of this code, one for holonomic and one not?)
</blockquote></details>

My new control law will never output a non-zero vy.

However, I agree that this code should work whether we're holonomic or not.  I have completely rewritten in a simpler fashion that should accomplish this.
___
*[src/teb_local_planner_ros.cpp, line 1172 at r9](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6g5gtCxckVZHBs4ci:-Lv7JuZSDm_yvrnW0fGR:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/ddba3634294d1986bde438711a213384112ce60d/src/teb_local_planner_ros.cpp#L1172)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't think we should delete the (very annoying) extra vertical WS here
</blockquote></details>

Done.
___
*[src/teb_local_planner_ros.cpp, line 56 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6jnuh11S9whkd-lX2:-Lv7HDA-CxcL7tREJSi2:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L56)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't know why the `g2o` includes above are using quotes `"`, but I think we should be using `<` and `>` for sure for including ros files.
</blockquote></details>

Done.
___
*[src/teb_local_planner_ros.cpp, line 66 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6kdAACTqcfyEt2Hmu:-Lv7VST78QJrjNYCUchV:b-4bqggu) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L66)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would strongly prefer these to be member variables over globals
</blockquote></details>

Whoops.  These were supposed to be temporary and not be committed.  So, I removed debug_interpolated_path_pub and related code (::visualizeInterpolatedPath()).

However, I like to keep debug_control_pose_pub, so I moved it to be a member.
___
*[src/teb_local_planner_ros.cpp, line 407 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6ljAX5etd5lPA14Ud:-Lv7kDVs4ZqLGAdwwWeY:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L407)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

dt never seems to be set to anything other than 1.0. Can we just remove it?
</blockquote></details>

Done.
___
*[src/teb_local_planner_ros.cpp, line 413 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6mSW6AlGlWRFF9NA2:-Lv7k65H43wurIUmiZRC:bsphiky) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L413)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

pretty sure the args to cos/sin should be `p1.theta + omega`, not p1.theta. Consider two poses like this:

```

             .---->


 .
/|\
 |
 |
```
If you use p1.theta, the new positions will all be on the direction the bottom vector is pointing (if its p1). If you use `p1.theta + omega`, they will be on the line that connects the bases of the poses. My guess is this causes no practical problems because  slerp_line is only ever used when going roughly in a straight line form poses to pose. However, for such a generally named function, either document the restriction in a comment, or change the calculation.
</blockquote></details>

Yeah.  I completely rewrite this function to be a simple weighted average of position & theta of the two poses.
___
*[src/teb_local_planner_ros.cpp, line 424 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6qi8X2N6bZgkwaW2h:-Lv7kYbdAwxYJ4XEuEmV:b-9ud2m1) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L424)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Won't this be a divide by zero if bearing is also +/- pi? Maybe slerp_arc should check if bearing is near 0 or pi and call slerp_line instead of slerp_pose doing it, as if some code in the future ever calls slerp_arc directly, you could get a division by zero.
</blockquote></details>

Well, I was actually trying to be more readable by separating the logic that decides which kind of slerp to do from the slerps. Doing what you suggest would be to basically combine slerp_pose and slerp_arc into one function, which I prefer not to do.  slerp_arc and slerp_line are just "sub-functions" of slerp_pose, not to be called directly.   Added a comment not to call this directly.
___
*[src/teb_local_planner_ros.cpp, line 425 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6rvYtDeuCgTSP5J0X:-Lv7lMwx2ADxf-oHYpNZ:b-oa1lyd) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L425)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Ah, I think I understand why, because such a curve would be un-achievable by a non-holonomic robot, as the bot would not be pointing in the direction of travel. 
</blockquote></details>

I'm slerping from the original pose's angle and double the bearing which is correct for following an arc-shaped trajectory.  True, p2 could theoretically have a different orientation, but that is, in effect, a contradiction, so neither theta is really correct. I prefer to just use the one lying on the arc.   In any case, the control law actually ignores the pose theta so it's not critical either way.
___
*[src/teb_local_planner_ros.cpp, line 440 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6q_fd5qxVRDqVS2IW:-Lv7mB7t2bsupliR2QE_:br8vot9) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L440)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I think you should also be checking for a bearing near +/- pi as that will cause a division by zero as well in slerp_arc
</blockquote></details>

Good Catch. Done.
___
*[src/teb_local_planner_ros.cpp, line 458 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6uY6HC-Pd0SVAEPrg:-Lv8E-WADzIw0P4-ZTu9:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L458)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't think the first check is necessary, pretty sure you can just simplify this to `seconds < cumulative_time + cur_time_diff`
</blockquote></details>

Done.
___
*[src/teb_local_planner_ros.cpp, line 478 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6smJj-fozgnIpGg9j:-Lv7niEwCOxzwX7vBDOu:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L478)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if start_time > end_time you will return whatever happens to be on the stack here. I would initialize this to `start_time`.
</blockquote></details>

Done.
___
*[src/teb_local_planner_ros.cpp, line 601 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6vZbp2R57neL7O75F:-Lv7nyjA2gDNtoNH1z5m:bkb5q41) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L601)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I assume the control point displacement is guaranteed to never be zero? Maybe make a comment here?
</blockquote></details>

Right. Added comment explaining why.

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r12, 1 of 1 files at r13, 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8)* status: all files reviewed, 3 unresolved discussions (waiting on @howardcochran)

___
*[src/teb_local_planner_ros.cpp, line 424 at r10](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv6qi8X2N6bZgkwaW2h:-Lv8LWCtC3coEXgCufuv:b-3ynzrf) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/c62e5b8e641a8cea92093bde751b9a5bec32235f/src/teb_local_planner_ros.cpp#L424)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Well, I was actually trying to be more readable by separating the logic that decides which kind of slerp to do from the slerps. Doing what you suggest would be to basically combine slerp_pose and slerp_arc into one function, which I prefer not to do.  slerp_arc and slerp_line are just "sub-functions" of slerp_pose, not to be called directly.   Added a comment not to call this directly.
</blockquote></details>

it might be a good idea if these are meant to be prviate to mark them `static` so they are file-local scope
___
*[src/teb_local_planner_ros.cpp, line 1066 at r16](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv8NWO-CSbuWcf2Wzvs:-Lv8NWO-CSbuWcf2Wzvt:bk0oode) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/30db0a4b49484f99be7314a5dc2711012468d16e/src/teb_local_planner_ros.cpp#L1066)):*
> ```cpp
>     scale = std::min(scale, -max_vel_x_backwards / vx);
>   if (max_vel_y > 1e-3 && std::abs(vy) > std::abs(max_vel_y))
>     scale = std::min(scale, std::abs(max_vel_y) / std::abs(vy));
> ```

very minor, but max_vel_y can't be negative here (you checked above), so you can drop the two occurrences of std::abs of max_vel_y
___
*[src/teb_local_planner_ros.cpp, line 1069 at r16](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv8NkqTCVQ2nYFS_TTH:-Lv8NkqTCVQ2nYFS_TTI:bj8syhm) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/30db0a4b49484f99be7314a5dc2711012468d16e/src/teb_local_planner_ros.cpp#L1069)):*
> ```cpp
>   if (std::abs(omega) > max_vel_theta)
>     scale = std::min(scale, max_vel_theta / std::abs(omega));
> ```

I think an `assert(0.0 < scale && scale <= 1.0);` would be prudent here to guard against logic issues

**Review by howardcochran — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-:-Lv8_m7o0j7OZwvWhS3K:bnfp4nl)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @c-andy-martin)

___
*[src/teb_local_planner_ros.cpp, line 1066 at r16](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv8NWO-CSbuWcf2Wzvs:-Lv8ZNvn-xPtWCgnV5gn:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/30db0a4b49484f99be7314a5dc2711012468d16e/src/teb_local_planner_ros.cpp#L1066)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

very minor, but max_vel_y can't be negative here (you checked above), so you can drop the two occurrences of std::abs of max_vel_y
</blockquote></details>

Done.
___
*[src/teb_local_planner_ros.cpp, line 1069 at r16](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8#-Lv8NkqTCVQ2nYFS_TTH:-Lv8_28q5O82EShXcarH:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/30db0a4b49484f99be7314a5dc2711012468d16e/src/teb_local_planner_ros.cpp#L1069)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I think an `assert(0.0 < scale && scale <= 1.0);` would be prudent here to guard against logic issues
</blockquote></details>

Done.

**Comment by c-andy-martin** [comment]
:lgtm:

**Review by c-andy-martin — APPROVED** [review]
> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
