### PR TITLE
add edges for nonlethal obstacles

### PR DESCRIPTION
**Pull request by c-andy-martin**
Costmaps can track obstacles that are inbetween the cost of free
space and lethal space. This can be useful when an object is detected,
such as a cord on the floor or a mat, that can be safely navigated,
but is better to be avoided if possible.

Add options to add edges for non-lethal obstacles. Add edge types
for Costmap3D, where querying the distance to only non-lethal obstacles
is possible.

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13)

### CODE REVIEW

**Review by howardcochran — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h, line 79 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PKcckDUzcHgwFeZf4:-M7PKcckDUzcHgwFeZf5:b-pquzvp) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h#L79)):*
> ```objc
>   {
>     costmap_3d_query_ = costmap_3d_query;
>     obstacle_dist_ = obstacle_dist;
> ```

Can you add min_ to this name.  It's confusing now because it reads as if this were the actual distance.
___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h, line 92 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PIsGt7gxg6d-LF5go:-M7PIsGt7gxg6d-LF5gp:b40s2px) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h#L92)):*
> ```objc
>     dopts.reuse_past_result = reuse_results;
>     dopts.query_obstacles = costmap_3d::Costmap3DQuery::NONLETHAL_ONLY;
> //    dopts.distance_limit = obstacle_dist_;
> ```

Remove commented-out code
___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h, line 97 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PJEyA-2h0c_fF64Np:-M7PJEyA-2h0c_fF64Nq:b39ofdt) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h#L97)):*
> ```objc
>     _error[0] = penaltyBoundFromBelow(dist, obstacle_dist_, 0.0);
> 
>     if (obstacle_cost_exponent_ != 1.0 && obstacle_dist_ > 0.0 && dist >= 0.0)
> ```

If this is not > 0.0, perhaps we just shoudn't attach this edge to the graph at all?
___
*[src/optimal_planner.cpp, line 1122 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PJoYY72paWOjkfNhg:-M7PJoYY72paWOjkfNhh:bunxp4l) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/src/optimal_planner.cpp#L1122)):*
> ```cpp
> 
>   // Nothing to do when the final result will always be zero
>   if (cfg_->optim.weight_nonlethal_obstacle == 0.0)
> ```

Add:
&& cfg_->obstacles.min_nonlethal_obstacle_dist > 0.0
___
*[src/optimal_planner.cpp, line 1136 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PK5ghASP7JGdjKJMW:-M7PK5ghASP7JGdjKJMX:b-ndnpol) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/src/optimal_planner.cpp#L1136)):*
> ```cpp
>     edge->setVertex(0, teb_.PoseVertex(i));
>     edge->setInformation(information);
>     edge->setTebConfig(*cfg_);
> ```

I don't think we need this because you're passing in all relevant config options to the constructor.

**Review by c-andy-martin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h, line 79 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PKcckDUzcHgwFeZf4:-M7tuAAY-I8dlOK58hJf:b-886gsx) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h#L79)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Can you add min_ to this name.  It's confusing now because it reads as if this were the actual distance.
</blockquote></details>

Fixed
___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h, line 92 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PIsGt7gxg6d-LF5go:-M7tu9HXBK6Jcf31Ixgx:b-886gsx) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h#L92)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Remove commented-out code
</blockquote></details>

Fixed
___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h, line 97 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PJEyA-2h0c_fF64Np:-M7tt-SEAlfF99eGuZ8y:bnchjts) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h#L97)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

If this is not > 0.0, perhaps we just shoudn't attach this edge to the graph at all?
</blockquote></details>

no, it makes sense to do so. It would mean, only do something when penetrating a maybe obstacle. In such a case, there is no use for the exponent (which is only used before contact). to make this clearer I'm explicitly setting signed_distance in the query options and renamed the returned value to signed_dist.
___
*[src/optimal_planner.cpp, line 1122 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PJoYY72paWOjkfNhg:-M7tt7Cz7royL3Uee_RH:b3lctuk) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/src/optimal_planner.cpp#L1122)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Add:
&& cfg_->obstacles.min_nonlethal_obstacle_dist > 0.0
</blockquote></details>

no, that is a valid value. it means you only care about collisions with maybes and want to avoid them.
___
*[src/optimal_planner.cpp, line 1136 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PK5ghASP7JGdjKJMW:-M7ttBOF7SdO1-ZFd_Q0:b-qt6oj4) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/src/optimal_planner.cpp#L1136)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I don't think we need this because you're passing in all relevant config options to the constructor.
</blockquote></details>

Good point. Fixed

**Review by howardcochran — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13)* status: all files reviewed, 2 unresolved discussions (waiting on @c-andy-martin)

___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h, line 97 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PJEyA-2h0c_fF64Np:-M8GbgVs-_69MQfW-pwL:b-cl6kg7) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h#L97)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

no, it makes sense to do so. It would mean, only do something when penetrating a maybe obstacle. In such a case, there is no use for the exponent (which is only used before contact). to make this clearer I'm explicitly setting signed_distance in the query options and renamed the returned value to signed_dist.
</blockquote></details>

So I still don't understand.... If min_obstacle_dist_ is 0.0, then this if clause will not run. Furthermore, the penaltyBoundFromBelow() call above will unconditionally set _error[0] to 0.0 no matter what signed_dist is.  So, it appears to me that this edge will always have a cost of zero and is therefore not going to affect the graph optimization at all.
___
*[src/optimal_planner.cpp, line 1122 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PJoYY72paWOjkfNhg:-M8GcEPEEaFXqxTFcPHy:b-9521xb) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/src/optimal_planner.cpp#L1122)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

no, that is a valid value. it means you only care about collisions with maybes and want to avoid them.
</blockquote></details>

See my related reply in the error function.

**Comment by c-andy-martin** [comment]
___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h, line 97 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PJEyA-2h0c_fF64Np:-M8H2PNR1LHn0D-Pu1g-:b-mjorwx) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h#L97)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

So I still don't understand.... If min_obstacle_dist_ is 0.0, then this if clause will not run. Furthermore, the penaltyBoundFromBelow() call above will unconditionally set _error[0] to 0.0 no matter what signed_dist is.  So, it appears to me that this edge will always have a cost of zero and is therefore not going to affect the graph optimization at all.
</blockquote></details>

penaltyBoundFromBelow will have a value when the signed_dist is zero or negative (its only bound is when the signed dist is over the min_obstacle_dist_). Perhaps you are thinking of penaltyBoundToInterval which bounds on both sides?

**Review by howardcochran — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h, line 97 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/13#-M7PJEyA-2h0c_fF64Np:-M8HD_b0D2akPwDHp5EL:b4c0lcr) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/b1e4d121c5205b5a01320f0988ac08c86dfa9089/include/teb_local_planner/g2o_types/edge_3d_costmap_nonlethal_only.h#L97)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

penaltyBoundFromBelow will have a value when the signed_dist is zero or negative (its only bound is when the signed dist is over the min_obstacle_dist_). Perhaps you are thinking of penaltyBoundToInterval which bounds on both sides?
</blockquote></details>

Oh, duh!  I forgot about that, heh.

**Pull request merged**
