### PR TITLE
add optional left-right obstacle inflation edges

### PR DESCRIPTION
**Pull request by c-andy-martin**
Add ability to optionally add left-right inflation edges to one or
more of the pose verteces. The left-right edges are inflation-only
edges where only obstacles to the left or right are taken into
account. The starting and stopping pose vertex are configurable, as
is the pose skip for adding edges. Also, the left and right exponents
and inflation distances are separate so an asymetry can be created
that is useful to cause the base to navigate on one side or other of
a corridor or aisle.

Currently this is only implemented when using Costmap3D.

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10)

### CODE REVIEW

**Review by howardcochran — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[cfg/TebLocalPlannerReconfigure.cfg, line 250 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40GCwJ-vwdObm1hzbe:-M40GCwJ-vwdObm1hzbf:b-bnznwn) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L250)):*
> ```INI
> 
> grp_obstacles.add("first_left_right_pose", int_t, 0,
> 	"First pose index on which to add left/right obstacle edges. "
> ```

Using mixed tabs & spaces for indention here!
___
*[cfg/TebLocalPlannerReconfigure.cfg, line 256 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40GLKF07DWt83q9fXV:-M40Fvjn34Z9DRkychDg:b-bnznwn) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L256)):*
> ```INI
> 
> grp_obstacles.add("last_left_right_pose", int_t, 0,
> 	"Last pose index on which to add left/right obstacle edges. "
> ```

Using mixed tabs & spaces for indention here!
___
*[cfg/TebLocalPlannerReconfigure.cfg, line 259 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40HFRcBb4mzqbBDgFl:-M40HFRcBb4mzqbBDgFm:bxn95tg) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L259)):*
> ```INI
>         "This helps reduce CPU load when in costmap 3D mode, "
>         "as left/right queries are more expensive.",
> 	0, 0, 100)
> ```

Should you have a value that means "the last possible pose"  (possibly -1)?
___
*[cfg/TebLocalPlannerReconfigure.cfg, line 262 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40GNAo8QpxcgVuKopS:-M40GNAo8QpxcgVuKopT:b-bnznwn) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L262)):*
> ```INI
> 
> grp_obstacles.add("left_right_skip_poses", int_t, 0,
> 	"Skip this many poses between adding left/right edges. "
> ```

Using mixed tabs & spaces for indention here!
___
*[cfg/TebLocalPlannerReconfigure.cfg, line 372 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40Go538ItvAVaqaLJ4:-M40Go538ItvAVaqaLJ5:brftoml) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L372)):*
> ```INI
> 
> grp_optimization.add("left_inflation_cost_exponent", double_t, 0,
> 	"Exponent for nonlinear left obstacle inflation cost (cost = left_inflation_dist * pow([fraction of possible inflation_cost], left_inflation_cost_exponent)). Set to 1 to disable nonlinear cost (default)",
> ```

Indention using tabs here
___
*[cfg/TebLocalPlannerReconfigure.cfg, line 376 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40GqB6-2dJwqrJbEwO:-M40GqB6-2dJwqrJbEwP:brftoml) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L376)):*
> ```INI
> 
> grp_optimization.add("right_inflation_cost_exponent", double_t, 0,
> 	"Exponent for nonlinear right obstacle inflation cost (cost = right_inflation_dist * pow([fraction of possible inflation_cost], right_inflation_cost_exponent)). Set to 1 to disable nonlinear cost (default)",
> ```

Indention using tabs here
___
*[src/optimal_planner.cpp, line 891 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40SmvjCmhwSE0mUuwg:-M40SmvjCmhwSE0mUuwh:b64emse) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/src/optimal_planner.cpp#L891)):*
> ```cpp
>   information(0,1) = information(1,0) = 0;
> 
>   bool add_left = false;
> ```

I would prefer all this left/right stuff be moved to a new function.
___
*[src/optimal_planner.cpp, line 895 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40S_ix0jfUqdm82bje:-M40S_ix0jfUqdm82bjf:b-xf4yob) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/src/optimal_planner.cpp#L895)):*
> ```cpp
>   int first_left_right_pose = 0;
>   int last_left_right_pose = 0;
>   int left_right_skip_count = 1;
> ```

Prefer a name like left_right_increment since it doesn't actually represent how many you're skipping (unlike the aptly named config parameter)

**Comment by c-andy-martin** [comment]
___
*[cfg/TebLocalPlannerReconfigure.cfg, line 250 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40GCwJ-vwdObm1hzbe:-M4pXfRV5ZKSoFga3nc-:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L250)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Using mixed tabs & spaces for indention here!
</blockquote></details>

Done.

**Comment by c-andy-martin** [comment]
___
*[cfg/TebLocalPlannerReconfigure.cfg, line 259 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40HFRcBb4mzqbBDgFl:-M4pXh9f9LtP61F9WgU8:b-uek9pb) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L259)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Should you have a value that means "the last possible pose"  (possibly -1)?
</blockquote></details>

Done. I actually made all negatives for both first/last be indexed from the end (similar to python).

**Review by c-andy-martin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[cfg/TebLocalPlannerReconfigure.cfg, line 256 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40GLKF07DWt83q9fXV:-M4pXgfxDKbsGJiGWIsw:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L256)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Using mixed tabs & spaces for indention here!
</blockquote></details>

Done.
___
*[cfg/TebLocalPlannerReconfigure.cfg, line 262 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40GNAo8QpxcgVuKopS:-M4pXq4o5DnRTxb17UqN:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L262)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Using mixed tabs & spaces for indention here!
</blockquote></details>

Done.

**Review by c-andy-martin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[cfg/TebLocalPlannerReconfigure.cfg, line 372 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40Go538ItvAVaqaLJ4:-M4pYI4lE8rtAdygGe8o:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L372)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Indention using tabs here
</blockquote></details>

Done.
___
*[cfg/TebLocalPlannerReconfigure.cfg, line 376 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40GqB6-2dJwqrJbEwO:-M4pYISV6fawMC2aA21A:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/cfg/TebLocalPlannerReconfigure.cfg#L376)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Indention using tabs here
</blockquote></details>

Done.
___
*[src/optimal_planner.cpp, line 891 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40SmvjCmhwSE0mUuwg:-M4pYSguCz-RB5LRnmeV:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/src/optimal_planner.cpp#L891)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I would prefer all this left/right stuff be moved to a new function.
</blockquote></details>

Done.
___
*[src/optimal_planner.cpp, line 895 at r1](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M40S_ix0jfUqdm82bje:-M4pYXQy3BCwYqE8OcQ3:b-896fix) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/262244c67efca1862cf1bc39724271a5a70b283c/src/optimal_planner.cpp#L895)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Prefer a name like left_right_increment since it doesn't actually represent how many you're skipping (unlike the aptly named config parameter)
</blockquote></details>

Done.

**Review by howardcochran — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10)* status: all files reviewed, 1 unresolved discussion (waiting on @c-andy-martin)

___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_left_right.h, line 95 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M4u2KVa0sA2H94ARdAg:-M4u2KVa0sA2H94ARdAh:b-3oa1rt) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/29a4ba897cd1a1df79bfd8f0ad931ad7da192b34/include/teb_local_planner/g2o_types/edge_3d_costmap_left_right.h#L95)):*
> ```objc
>     double inflation_dist = 0.0;
>     double inflation_cost_exponent = 1.0;
>     if (region == costmap_3d::Costmap3DQuery::LEFT)
> ```

Discussion:
If region were a constructor parameter rather than a template parameter, then there would only be one type, which would reduce duplicated code in AddEdges...()

Furthermore, if inflation_dist and inflation_cost_exponent were constructor parameters, then the logic here would not be needed.

Alternatively, make all three be template params, get rid of this logic, but retain the duplication in AddEdges...().

Or leave it the way it is.
___
*[src/optimal_planner.cpp, line 914 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M4toOzP1ef0oNHcYz7W:-M4toOzP1ef0oNHcYz7X:b6tbu2v) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/29a4ba897cd1a1df79bfd8f0ad931ad7da192b34/src/optimal_planner.cpp#L914)):*
> ```cpp
>   int step_count = 1;
>   Eigen::Matrix<double,1,1> information;
> ```

Just a mild suggestion. It's OK to leave this alone:
Would you mind making the following section a bit more concise?  Something like:

    bool add_left = (cfg_->obstacles.left_inflation_dist > cfg_->obstacles.min_obstacle_dist);
    bool add_right = ...;
    if (!add_left && !add_right)
    {
        return;
    }
... then use std::min & std::max to do the clamping.  (Unfortunately, std::clamp is C++17).

**Review by c-andy-martin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @c-andy-martin and @howardcochran)

___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_left_right.h, line 95 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M4u2KVa0sA2H94ARdAg:-M5yLi_14nLsfWehKRzC:b-uzcv4i) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/29a4ba897cd1a1df79bfd8f0ad931ad7da192b34/include/teb_local_planner/g2o_types/edge_3d_costmap_left_right.h#L95)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Discussion:
If region were a constructor parameter rather than a template parameter, then there would only be one type, which would reduce duplicated code in AddEdges...()

Furthermore, if inflation_dist and inflation_cost_exponent were constructor parameters, then the logic here would not be needed.

Alternatively, make all three be template params, get rid of this logic, but retain the duplication in AddEdges...().

Or leave it the way it is.
</blockquote></details>

I have followed your idea and simplified accordingly.
___
*[src/optimal_planner.cpp, line 914 at r2](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M4toOzP1ef0oNHcYz7W:-M5yLczFCemYNsQ7fdIt:btdf02q) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/29a4ba897cd1a1df79bfd8f0ad931ad7da192b34/src/optimal_planner.cpp#L914)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Just a mild suggestion. It's OK to leave this alone:
Would you mind making the following section a bit more concise?  Something like:

    bool add_left = (cfg_->obstacles.left_inflation_dist > cfg_->obstacles.min_obstacle_dist);
    bool add_right = ...;
    if (!add_left && !add_right)
    {
        return;
    }
... then use std::min & std::max to do the clamping.  (Unfortunately, std::clamp is C++17).


</blockquote></details>

Done. I followed your advice here and simplified everything accordingly.

**Review by howardcochran — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_left_right.h, line 101 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M6G0uYqAqzTPvQg9mSk:-M6G0uYr3xKxomxMUFk9:b-ywe4vs) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/d7362d7db40a7b7fab4359f34ad60f6b4b803444/include/teb_local_planner/g2o_types/edge_3d_costmap_left_right.h#L101)):*
> ```objc
>     if (inflation_cost_exponent_ != 1.0 && inflation_dist_ > 0.0 && dist >= 0.0)
>     {
>       // Optional non-linear inflation cost. See comment above about obstacle_cost_exponent.
> ```

I think this comment is out of date
___
*[src/teb_local_planner_ros.cpp, line 144 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M6G44jIEeJ0rOTq0nLC:-M6G44jJEWF61AI-ZJdu:b7cqivx) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/d7362d7db40a7b7fab4359f34ad60f6b4b803444/src/teb_local_planner_ros.cpp#L144)):*
> ```cpp
>       planner_->useCostmap3DQuery(costmap_3d_query_);
>       // Override the costmap model with a Costmap3DModel
>       auto costmap_3d_model_ = boost::make_shared<base_local_planner::Costmap3DModel>(*costmap_3d_ros_);
> ```

Why are you naming a local variable as if it were a member variable?

**Review by howardcochran — COMMENTED** [review]
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10)* status: all files reviewed, 2 unresolved discussions (waiting on @c-andy-martin)

**Comment by c-andy-martin** [comment]
___
*[include/teb_local_planner/g2o_types/edge_3d_costmap_left_right.h, line 101 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M6G0uYqAqzTPvQg9mSk:-M6G8-Ta6KQbPnTauPX0:b-97t5c2) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/d7362d7db40a7b7fab4359f34ad60f6b4b803444/include/teb_local_planner/g2o_types/edge_3d_costmap_left_right.h#L101)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I think this comment is out of date
</blockquote></details>

good point. Fixed.

**Review by c-andy-martin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @howardcochran)

___
*[src/teb_local_planner_ros.cpp, line 144 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10#-M6G44jIEeJ0rOTq0nLC:-M6G83mEELZ-P9UneGzz:b-9qucfm) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/d7362d7db40a7b7fab4359f34ad60f6b4b803444/src/teb_local_planner_ros.cpp#L144)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Why are you naming a local variable as if it were a member variable?
</blockquote></details>

At one point in my history it was a member, then I realized I already had it as a member pointer to the base class, and forgot to change the name. Good catch! Fixed.

**Review by howardcochran — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
