### PR TITLE
Port gtest-built unittests to run in yocto

### PR DESCRIPTION
**Pull request by bobhenz-jabil**
Related PR: https://github.com/BadgerTechnologies/badger_lib/pull/103

This change is [Reviewable](https://reviewable.io/reviews/BadgerTechnologies/teb_local_planner/21)

### CODE REVIEW

**Comment by bobhenz-jabil** [comment]
This broke running these tests through catkin. I need to determine why before I this PR can move forward.

**Comment by bobhenz-jabil** [comment]
Fixed

**Review by travisariggs — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/teb_local_planner/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bobhenz-jabil)

**Review by KendallRanConley — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/teb_local_planner/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bobhenz-jabil)

**Pull request merged**
