### PR TITLE
Fix control law rotational instability

### PR DESCRIPTION
**Pull request by c-andy-martin**
Have the control law turn in place when near the carrot pose, and also fix a couple of bugs.

    The previous implementation of the control law special cased a
    rotation in place when near the goal, and looked ahead on the path
    until the carrot was at least carrot_min_dist away. However, if the
    path contains a spiral such that the pose min_carrot_dist away is
    significantly different in orientation than the current orientation
    the control law poorly follows the plan, sometimes turning the wrong
    way.
    
    Deal with this by generalizing the turn-in-place control to activate
    any time the carrot pose at time delta carrot_dt is within
    carrot_min_dist. When the carrot pose is not at the goal, simply
    issue the direct rotational velocity to follow the rotation in the
    plan. If the carrot pose is at the goal, use the P controller to
    prevent over-shooting the goal.
    
    Since turn in place can now happen anywhere along the path, remove
    the now unneeded turn_in_place_goal_dist configuration parameter.

Also fix an interpolation issue when two poses are mostly strafing, and fix a bug in slerp_line.

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/16)

### CODE REVIEW

**Review by howardcochran — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/16)* status: all files reviewed, 3 unresolved discussions (waiting on @c-andy-martin)

___
*[src/teb_config.cpp, line 88 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/16#-MKuAk-197teQCgmzoBA:-MKuAk-22WlQRnZ-uY1h:b-5lq4kq) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/a57bbf431ead0768a354d21c06fede92562c3f02/src/teb_config.cpp#L88)):*
> ```cpp
>   nh.param("carrot_min_dist", control.carrot_min_dist, control.carrot_min_dist);
>   nh.param("carrot_min_angle", control.carrot_min_angle, control.carrot_min_angle);
>   nh.param("turn_in_place_dist", control.turn_in_place_dist, control.turn_in_place_dist);
> ```

Would prefer this be called turn_in_place_carrot_dist to give it some context.
___
*[src/teb_local_planner_ros.cpp, line 572 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/16#-MKuBDQ67rMxlonAi59i:-MKuBDQ67rMxlonAi59j:b-7fi55q) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/a57bbf431ead0768a354d21c06fede92562c3f02/src/teb_local_planner_ros.cpp#L572)):*
> ```cpp
>   {
>     carrot_pose = interpolatePath(*teb, robot_time + dt);
>     delta_carrot = carrot_pose.position() - robot_pose.position();
> ```

Sorry to be a sticker for names, but now that we have two different deltas here, the name delta_carrot is to unspecific.
I propose the following renaming:
delta_carrot -> delta_pos

OR, perhaps better:

delta_carrot -> carrot_dpos
delta_theta -> carrot_dtheta
___
*[src/teb_local_planner_ros.cpp, line 613 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/16#-MKuCYFr1aXQwVpYWyq-:-MKuCYFr1aXQwVpYWyq0:btq7j9y) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/a57bbf431ead0768a354d21c06fede92562c3f02/src/teb_local_planner_ros.cpp#L613)):*
> ```cpp
>       else
>       {
>         robot_at_goal = true;
> ```

I feel that this robot_at_goal boolean is unnecessary.  Just set cmd_vel.angular.z to zero here and dispense with the boolean.  

The else case (!robot_at_goal) would execute unconditionally, but all it would do is copy a harmless sign onto a zero.  If that mattered (and I think it does not), one could make that conditional on .angular.z != 0 instead of this extra boolean.

What do you think?

**Review by c-andy-martin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/16)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @howardcochran)

___
*[src/teb_config.cpp, line 88 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/16#-MKuAk-197teQCgmzoBA:-MKuU7EUC95IPzuTFPah:b-edvhnt) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/a57bbf431ead0768a354d21c06fede92562c3f02/src/teb_config.cpp#L88)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Would prefer this be called turn_in_place_carrot_dist to give it some context.
</blockquote></details>

Done. I also cleaned up the description to match.
___
*[src/teb_local_planner_ros.cpp, line 572 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/16#-MKuBDQ67rMxlonAi59i:-MKuU1T-DUHirz2PBtMK:b32ql8w) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/a57bbf431ead0768a354d21c06fede92562c3f02/src/teb_local_planner_ros.cpp#L572)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Sorry to be a sticker for names, but now that we have two different deltas here, the name delta_carrot is to unspecific.
I propose the following renaming:
delta_carrot -> delta_pos

OR, perhaps better:

delta_carrot -> carrot_dpos
delta_theta -> carrot_dtheta
</blockquote></details>

Done. I went with the even more complete `delta_carrot_position` and `delta_carrot_angle`.
___
*[src/teb_local_planner_ros.cpp, line 613 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/16#-MKuCYFr1aXQwVpYWyq-:-MKuOCWW6LR0COciNqy8:b-v4e4lf) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/a57bbf431ead0768a354d21c06fede92562c3f02/src/teb_local_planner_ros.cpp#L613)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I feel that this robot_at_goal boolean is unnecessary.  Just set cmd_vel.angular.z to zero here and dispense with the boolean.  

The else case (!robot_at_goal) would execute unconditionally, but all it would do is copy a harmless sign onto a zero.  If that mattered (and I think it does not), one could make that conditional on .angular.z != 0 instead of this extra boolean.

What do you think?
</blockquote></details>

So, if the logic when we are not `robot_at_goal` comes up with a zero velocity, I want to enforce the minimum velocity and force the robot to move somewhere. However, if `robot_at_goal` I want to force zero velocity. I also want to apply the minimum velocity after I apply Kp if the carrot pose is at the goal. I came up with the boolean to make the code somewhat readable for these various cases. If I do as you suggest, with no other changes, when robot_at_goal, we will copy the sign of zero onto min_vel_theta and end up w/ min_vel_theta instead of zero (which is not what we want). If I test for zero velocity, I don't handle the case that delta_theta was zero when the robot is not at the goal (this could happen if the configuration is such that the min carrot dist is smaller than both the xy goal tolerance and the turn in place dist and we have no angular change).

**Comment by howardcochran** [comment]
___
*[src/teb_local_planner_ros.cpp, line 613 at r3](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/16#-MKuCYFr1aXQwVpYWyq-:-MKu_UYZ9rXOV5An_Iin:b6ug36a) ([raw file](https://github.com/badgertechnologies/teb_local_planner/blob/a57bbf431ead0768a354d21c06fede92562c3f02/src/teb_local_planner_ros.cpp#L613)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

So, if the logic when we are not `robot_at_goal` comes up with a zero velocity, I want to enforce the minimum velocity and force the robot to move somewhere. However, if `robot_at_goal` I want to force zero velocity. I also want to apply the minimum velocity after I apply Kp if the carrot pose is at the goal. I came up with the boolean to make the code somewhat readable for these various cases. If I do as you suggest, with no other changes, when robot_at_goal, we will copy the sign of zero onto min_vel_theta and end up w/ min_vel_theta instead of zero (which is not what we want). If I test for zero velocity, I don't handle the case that delta_theta was zero when the robot is not at the goal (this could happen if the configuration is such that the min carrot dist is smaller than both the xy goal tolerance and the turn in place dist and we have no angular change).
</blockquote></details>

Yeah, I misread the else case totally.  My bad.

**Review by howardcochran — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/teb_local_planner/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
